// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAXdt6WqDX58O7FiogOnfUtWM3jTII584',
    appId: '1:839365380371:web:648f279c814add822b72e6',
    messagingSenderId: '839365380371',
    projectId: 'flexpay-app-77b85',
    authDomain: 'flexpay-app-77b85.firebaseapp.com',
    storageBucket: 'flexpay-app-77b85.firebasestorage.app',
    measurementId: 'G-D78BGSGK2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrSeHNzdjixquixau1PSF0DZi0JASRHGc',
    appId: '1:839365380371:android:f4dc1d9d2948b84d2b72e6',
    messagingSenderId: '839365380371',
    projectId: 'flexpay-app-77b85',
    storageBucket: 'flexpay-app-77b85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzB1Jnzz-g9upjdC8i7ndw3Bt4bG3nbzw',
    appId: '1:839365380371:ios:5f95f07c8dd869db2b72e6',
    messagingSenderId: '839365380371',
    projectId: 'flexpay-app-77b85',
    storageBucket: 'flexpay-app-77b85.firebasestorage.app',
    iosBundleId: 'com.example.flexpayNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzB1Jnzz-g9upjdC8i7ndw3Bt4bG3nbzw',
    appId: '1:839365380371:ios:5f95f07c8dd869db2b72e6',
    messagingSenderId: '839365380371',
    projectId: 'flexpay-app-77b85',
    storageBucket: 'flexpay-app-77b85.firebasestorage.app',
    iosBundleId: 'com.example.flexpayNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAXdt6WqDX58O7FiogOnfUtWM3jTII584',
    appId: '1:839365380371:web:edcb4810ac66e82c2b72e6',
    messagingSenderId: '839365380371',
    projectId: 'flexpay-app-77b85',
    authDomain: 'flexpay-app-77b85.firebaseapp.com',
    storageBucket: 'flexpay-app-77b85.firebasestorage.app',
    measurementId: 'G-CFEB4VZZ2X',
  );
}
